import { useState } from 'react'
import type { Expense } from '../../types'
import { Card } from '../../components/ui/Card'
import { DataTable } from '../../components/ui/Table'

const categories = ['Stock/Purchases','Transport','Fuel','Warehouse','Staff','Utilities','Equipment','Professional Fees','Marketing','Repairs','Other']
const initial = { title:'', category:'Stock/Purchases', supplier:'', amount:'', currency:'GBP', expenseDate:new Date().toISOString().slice(0,10), description:'', paymentMethod:'Bank Transfer', reference:'' }
export function ExpensesPage({ expenses, userName, onCreate, onDelete }: { expenses: Expense[]; userName: string; onCreate:(x:Omit<Expense,'id'|'createdAt'>)=>Promise<void>; onDelete:(id:string)=>Promise<void> }) {
  const [form,setForm]=useState(initial), [show,setShow]=useState(false), [busy,setBusy]=useState(false), [error,setError]=useState('')
  const total=expenses.reduce((s,x)=>s+x.amount,0)
  const save=async()=>{ if(!form.title.trim()||Number(form.amount)<=0){setError('Expense title and a positive amount are required.');return} setBusy(true);setError('');try{await onCreate({...form,amount:Number(form.amount),recordedBy:userName});setForm(initial);setShow(false)}catch{setError('Could not record the expense.')}finally{setBusy(false)} }
  return <div className="stack"><div className="page-heading"><div><h1>Expenses</h1><p>Record operating costs and receipts for synchronized finance reporting.</p></div><button className="btn btn-primary" onClick={()=>setShow(true)}>+ Record Expense</button></div><div className="overview-grid"><Card title="Total Expenses"><p className="metric">£{total.toFixed(2)}</p></Card><Card title="Expense Records"><p className="metric">{expenses.length}</p></Card></div>{show&&<Card title="Record Expense"><div className="form-grid">{[['title','Expense Title'],['supplier','Supplier / Payee'],['amount','Amount'],['reference','Reference']].map(([k,l])=><label className="form-control" key={k}><span>{l}</span><input type={k==='amount'?'number':'text'} value={form[k as keyof typeof form]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label className="form-control"><span>Category</span><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label className="form-control"><span>Expense Date</span><input type="date" value={form.expenseDate} onChange={e=>setForm({...form,expenseDate:e.target.value})}/></label><label className="form-control"><span>Payment Method</span><input value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value})}/></label><label className="form-control wide"><span>Description</span><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div>{error&&<p className="error-message">{error}</p>}<div className="actions-row"><button className="btn btn-primary" disabled={busy} onClick={save}>{busy?'Saving...':'Save Expense'}</button><button className="btn btn-secondary" onClick={()=>setShow(false)}>Cancel</button></div></Card>}<Card title="Expense History"><DataTable columns={['Date','Title','Category','Supplier','Method','Reference','Recorded By','Amount','Actions']}>{expenses.map(x=><tr key={x.id}><td>{x.expenseDate}</td><td><strong>{x.title}</strong></td><td>{x.category}</td><td>{x.supplier||'—'}</td><td>{x.paymentMethod}</td><td>{x.reference||'—'}</td><td>{x.recordedBy}</td><td>£{x.amount.toFixed(2)}</td><td><button className="btn btn-danger btn-sm" onClick={()=>window.confirm(`Delete expense ${x.title}?`)&&onDelete(x.id)}>Delete</button></td></tr>)}</DataTable></Card></div>
}
